### ISSUE TITLE
Do you have a plan to support. net core?

### ISSUE THREAD

**Issue by warmthlee** [Ormikon/OWIN-Static#4]
Hi @Ormikon !
I used this project as a static server to manager my css、js、img files. And It works well.

In my place, I will implement a SAAS platform and eventually use dorker deployment. So I'm very concerned about whether you have a plan to support . net core.

Thank you for creating this project.  Looking forward to your reply.

**Comment by Ormikon** [comment]
Hi @warmthlee 
Sorry, have no time to support this project. And looks like this is my last change here...
Migrated it to asp.net core: https://www.nuget.org/packages/Ormikon.AspNetCore.Static/0.4.0
